name = "Zoom"
description = "Call Zoom API."
logo_url = "https://storage.googleapis.com/lutra-2407-public/400ce0579863533a48d310b35811638393dbc50d4fbed9e5045ee43ceaa3f8ac.svg"

[[required_actions]]
action_reference_type = "augmented_request"
augmented_request_configuration_id = "5874e9f1-e629-4844-96de-5f8ba2df0742"
