name = "Xerp"
description = "Manage your Xero account, invoices, bills and more"
logo_url = "https://storage.googleapis.com/lutra-2407-public/d57d1f501344bcd670537713c949bf66cedf5cac401ee2b04505a39432348464.svg"
