name = "GitHub"
description = "Get information about GitHub pull requests and issues."
logo_url = "https://storage.googleapis.com/lutra-2407-public/7a0dd11e373830a51a565de9fed4a985707c67ccd390f9ae4946a152303ea676.svg"

[[required_actions]]
action_reference_type = "augmented_request"
augmented_request_configuration_id = "2598dbb1-c887-4151-a833-78760eebf6bd"
