name = "GitHub"
description = "Get information about GitHub pull requests and issues."
logo_url = "https://storage.googleapis.com/lutra-2407-public/7a0dd11e373830a51a565de9fed4a985707c67ccd390f9ae4946a152303ea676.svg"
