name = "GitHub"
description = "Use GitHub."
logo_url = "file:/assets/logos/github-mark.svg"

[[required_actions]]
action_reference_type = "augmented_request"
augmented_request_configuration_id = "2598dbb1-c887-4151-a833-78760eebf6bd"
